pipeline{
	agent any
	
	stages{
		
		stage ('Compile Stage'){
			steps{
				withMaven(maven : 'maven_3.6.0'){
					bat 'mvn -f MapBoxJS\pom.xml clean compile'
				}
			}
		}
		
		stage ('Testing Stage'){
			steps{
				withMaven(maven : 'maven_3.6.0'){
					bat 'mvn -f MapBoxJS\pom.xml test'
				}
			}
		}
		
		stage ('Deployment Stage'){
			steps{
				withMaven(maven : 'maven_3.6.0'){
					bat 'mvn -f MapBoxJS\pom.xml deploy'
				}
			}
		}
		
	}
}